In [1]:
import logic
import importlib
importlib.reload(logic)

<module 'logic' from 'c:\\workspace\\unimore-bioinfo-exam\\logic.py'>

In [2]:
#logic.set_all_seeds(42)

In [3]:
features, labels = logic.data_preparation("dataset_LUMINAL_A_B.csv", 40)

In [4]:
print(features.shape)
print(features)

print(labels.shape)
print(labels)

torch.Size([100, 40])
tensor([[ 8.1851e+01,  6.6550e+01,  1.2008e+00,  ..., -6.4278e-02,
          5.0725e-02, -7.9872e-02],
        [-5.4433e+00, -6.8503e-01,  2.3628e+00,  ...,  1.7762e+00,
         -2.0182e+00,  6.0600e-01],
        [-7.9172e-01, -7.5668e-01, -2.9498e+00,  ..., -2.0376e+00,
          2.7772e+00,  7.9441e-01],
        ...,
        [-3.8432e+00,  4.5424e-01,  7.6024e+00,  ...,  1.7117e-01,
         -4.3669e-01, -6.5767e-01],
        [-6.2338e-01, -8.1303e-01, -3.9150e+00,  ..., -3.1851e+00,
         -3.6376e-01,  3.1149e+00],
        [-1.6019e+00,  8.8208e-01, -7.8587e+00,  ...,  2.8983e+00,
         -1.8388e+00,  4.0557e+00]])
torch.Size([100])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        

In [5]:
correlation = logic.compute_abs_pearson_correlation(features)

In [6]:
print(correlation)

tensor([[1.0000, 0.2425, 0.1035,  ..., 0.0671, 0.0289, 0.0221],
        [0.2425, 1.0000, 0.2399,  ..., 0.0867, 0.0499, 0.0673],
        [0.1035, 0.2399, 1.0000,  ..., 0.1203, 0.1395, 0.0764],
        ...,
        [0.0671, 0.0867, 0.1203,  ..., 1.0000, 0.0639, 0.0381],
        [0.0289, 0.0499, 0.1395,  ..., 0.0639, 1.0000, 0.0632],
        [0.0221, 0.0673, 0.0764,  ..., 0.0381, 0.0632, 1.0000]])


In [7]:
edges = logic.create_sparse_edges_with_threshold(correlation, 0.4)

In [8]:
print(edges)

tensor([[ 0,  1,  1,  1,  2,  2,  3,  3,  3,  4,  4,  4,  4,  4,  5,  6,  6,  6,
          6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  8,  9, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 11, 11, 11, 14, 14, 14, 14, 14, 14, 14, 15, 15,
         15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 18, 18, 18, 18, 20,
         21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22,
         22, 22, 22, 22, 22, 22, 23, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
         26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 28, 28, 28, 28, 28, 28, 29,
         29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30,
         31, 31, 31, 32, 32, 32, 32, 32, 32, 32, 32, 34, 34, 34, 34, 34, 34, 34,
         34, 34, 34, 34, 34, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 36, 36,
         36, 36, 36, 37, 38, 38, 38, 38, 38, 40, 40, 42, 43, 43, 43, 43, 44, 44,
         45, 45, 45, 45, 45, 45, 45, 45, 45, 47, 47, 49, 49, 49, 49, 49, 49, 49,
         50, 51, 51, 52, 53,

In [9]:
number_of_points = features.shape[0]
train_mask, test_mask = logic.prepare_dataset_masks(number_of_points)

In [10]:
model = logic.GCN(input_channels=features.shape[1], hidden_channels=8, output_channels=2)
logic.train_gnn(model, 100, features, labels, edges, train_mask, verbose=False)
test_accuracy = logic.test_gnn(model, features, labels, edges, test_mask)
print(f"Test Accuracy: {test_accuracy:.4f}")

Test Accuracy: 0.8143
